### ISSUE TITLE
Spacing of isotope and stable/unstable labels on Make Isotope screen

### ISSUE THREAD

**Issue by amyh-phet** [phetsims/isotopes-and-atomic-mass#27] opened 2016-01-08 16:09 UTC
When the user builds different isotopes by adding neutrons to the nucleus, the labels pop up (or down) as the user selects and drags the neutrons.   Can we have the isotope name (e.g. Hydrogen-1) and the stable/unstable labels placed at a set location based on the maximum size of the nucleus?  If needed, the size of the protons and neutrons can be reduced slightly to accommodate the labels.

Stable/unstable is partially occluded for Helium-7 and Helium-8

**Comment by aadish** [comment] 2016-01-12 22:56
duplicate of #21, closing

**Closed by aadish** 2016-01-12 22:56 UTC
