### ISSUE TITLE
CT cannot read property globalToLocalPoint of undefined

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#102] opened 2021-02-05 16:36 UTC
```
isotopes-and-atomic-mass : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612485936684%22%2C%22timestamp%22%3A1612492121665%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught TypeError: Cannot read property 'globalToLocalPoint' of undefined
TypeError: Cannot read property 'globalToLocalPoint' of undefined
at localViewToModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/shred/js/view/BucketDragListener.js:38:37)
at BucketDragListener.drag [as _dragListener] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/shred/js/view/BucketDragListener.js:57:53)
at BucketDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/scenery/js/listeners/PressListener.js:446:10)
at DragListener._dragAction.Action.parameters.name (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/scenery/js/listeners/DragListener.js:244:36)
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/axon/js/Action.js:225:18)
at BucketDragListener.drag (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/scenery/js/listeners/DragListener.js:363:22)
at BucketDragListener.pointerMove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/scenery/js/listeners/PressListener.js:809:14)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/scenery/js/input/Input.js:1832:25)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/scenery/js/input/Input.js:1781:10)
at Input.branchChangeEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612485936684/scenery/js/input/Input.js:1681:12)
id: Bayes Chrome
Snapshot from 2/4/2021, 5:45:36 PM
```

**Comment by jbphet** [comment] 2021-02-05 21:22
Here's how to duplicate this manually:
- go to the 2nd screen
- using a finger, touch a bucket and drag so that a particle is extracted
- drag the particle away from the bucket, but continue to hold on to it
- with another finger, select the "slider" radio button from the bucket-slider radio buttons at the bottom of the test chamber (the black rectangle)

**Comment by jbphet** [comment] 2021-02-05 22:00
I did a bunch of code cleanup and fixed a different multi-touch issue as part of the commit to address this, so I should explain what was happening and what fixed it.

The problem was caused by drag listeners on the isotope buckets that were still operating after the bucket node had been removed from the scene graph.  To address the problem, I added code to interrupt user input on the bucket.  It was in `MixIsotopesScreenView.js` and looks like this:
```
          bucketFront.interruptSubtreeInput(); // cancel any in-progress interactions, prevents multi-touch issues
```

**Comment by jbphet** [comment] 2021-02-05 22:01
@KatieWoe - I'd like some regression testing done on the master version of this sim to verify that this didn't break anything.  The testing should focus on interactions with the buckets on the 2nd screen.

**Comment by KatieWoe** [comment] 2021-02-05 22:31
https://github.com/phetsims/isotopes-and-atomic-mass/issues/101#issuecomment-774323790

**Comment by jbphet** [comment] 2021-02-09 16:50
Back to QA for more regression testing, see https://github.com/phetsims/isotopes-and-atomic-mass/issues/101#issuecomment-776079434.

**Comment by KatieWoe** [comment] 2021-02-09 17:45
https://github.com/phetsims/isotopes-and-atomic-mass/issues/101#issuecomment-776117999

**Comment by jbphet** [comment] 2021-02-09 17:48
Okay, it seems like #101 and this one have become stuck together.  I'm going to close this one and assume that we will tackle everything resulting from the multi-touch fuzz testing under #101.

**Closed by jbphet** 2021-02-09 17:48 UTC
Labels: type:automated-testing
