### ISSUE TITLE
Inconsistencies with reset button

### ISSUE THREAD

**Issue by bryo5363** [phetsims/isotopes-and-atomic-mass#23] opened 2015-12-29 20:48 UTC
I noticed that the drop down displays on the 'Make Isotopes' section of the sim are initially compressed while the drop down displays on the 'Mix Isotopes' are initially expanded. I added the question tag because I didn't know if this is intentional or not.

**Comment by aadish** [comment] 2016-01-12 22:49
@jbphet says this was by design, closing

**Closed by aadish** 2016-01-12 22:49 UTC
Labels: question
